# Generated by Django 4.0.8 on 2022-12-13 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank='', default='0', max_length=100)),
                ('card_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('card_name', models.CharField(blank='', default=0, max_length=100)),
                ('expire', models.CharField(blank='', default='0', max_length=10)),
                ('cvv', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
